### ISSUE TITLE
adapt parenthesized expressions

### ISSUE THREAD

**Issue by Roadagain** [kosen13s/tiny#13]
next, adapt tiny to bracketed expressions!

**Comment by Iruyan-Zak** [comment]
Why not adding `Parenthesized [Token]` constructor to `Token` ?
I think to specialize parenthesized tokens makes the implements simple.

Does anyone have (tiny|concrete) idea?

**Comment by Roadagain** [comment]
great, i'm gonna do it.

**Comment by Roadagain** [comment]
i guessed `Parenthesized` node will have only one Tree, so it seems like an edge.
is it really needed?

if construct from `"(1+2)*3"`, the tree should be like this:
```
    *
   / \
  +   3
 / \
1   2
```
if it is not, i need some reasons to understand.

**Comment by Iruyan-Zak** [comment]
All right.
You can leave parenthesized operator, but it is not important.

In lexical parser layer, I send you `Parenthesized` token, so I leave how treat it to you .

**Comment by Iruyan-Zak** [comment]
I implemented `parenthesized` parser.
If it has no problem, please merge and engage in syntactic approach.

**Comment by Roadagain** [comment]
i have merged it.
great job :+1:

**Comment by Iruyan-Zak** [comment]
Looks good!
Can I merge this commit?

**Comment by Roadagain** [comment]
sorry to be late, PR was created.
please merge it!

**Comment by Roadagain** [comment]
close via #14 and #17.
