### ISSUE TITLE
write comment and unify commenting format

### ISSUE THREAD

**Issue by Iruyan-Zak** [kosen13s/tiny#16]
And I suggest to unify a format of commenting now.

**Comment by Iruyan-Zak** [comment]
My format is
```
-- |
-- (comments with line breaks per sentences without blank line)
-- (blank line)
-- >>> (doctest codes without blank line)
-- (blank line)
(function type definition)
```

**Comment by Iruyan-Zak** [comment]
Sorry, I forgot writing a comment on TinyParser.hs/`between`.
I rename this issue and fix here.

**Comment by Roadagain** [comment]
i wrote comments as your format.
please check it if you have time.

**Comment by Iruyan-Zak** [comment]
Even if not to the all, I ask you to attach some use of functions by the form of DocTest,  please.

**Comment by Roadagain** [comment]
`TreeState` includes a function in itself, so it is difficult to attach doctest.
do others satisfy your need?

**Comment by Roadagain** [comment]
thx to add doctest.
so can i create PR to `develop` ?
