### ISSUE TITLE
Noting specfications

### ISSUE THREAD

**Issue by Roadagain** [kosen13s/tiny#22]
we should note specifications, but we dont.
lets discuss how to do it.

**Comment by Iruyan-Zak** [comment]
In my head,

- Concept(Features of this language)
- Examples of syntax
- Draft(Summary of arguments)

help our development.

**Comment by Iruyan-Zak** [comment]
Keeping it is useful for explaining what we do and understanding the outline of development to our solutions for language creation tasks.

**Comment by Roadagain** [comment]
great, note to [wiki](https://github.com/kosen13s/tiny/wiki)?

**Comment by Iruyan-Zak** [comment]
Yeah.

**Comment by Roadagain** [comment]
*Draft* means drafts of implementing features, right?

**Comment by Iruyan-Zak** [comment]
Mainly, all of our temporary decision argued on Slack, including yours.

**Comment by Roadagain** [comment]
wiki creation has been done.
can i close this issue?

**Comment by Iruyan-Zak** [comment]
OK.
And then create an issue about expansion of specifications.
