### ISSUE TITLE
Parsing four-arithmetical-operation

### ISSUE THREAD

**Issue by Iruyan-Zak** [kosen13s/tiny#5]
Let's parse four-arithmetical-operation!

I wonder if...
- how to recover errors. (use monad-transformer? or more simply, use only Either monad?)
- what I implement, (at least `+`, `-`, `*`, `/`, but other component in this issue? e.g. `()`, `mod`.)

**Comment by Roadagain** [comment]
i viewed your 1+1 parser on `four-arithmetical-operation` .
i guess we should make the numerical parser first: sounds easy to extend to the operation parser.

i would like you to tell me your own opinion.

**Comment by Iruyan-Zak** [comment]
In my code...
```
    (lhs, s1) <- char '1' str
    (plus, s2) <- char '+' s1
    (rhs, s3) <- char '1' s2
```

I prefer below one.
```
    lhs <- char '1'
    plus <- char '+'
    rhs <- char '1'
```

This is just a motivation to use State monad.
So next, I'd like to adopt State monad before my code becomes complicated.

**Comment by Roadagain** [comment]
i see. do what you'd love to do.
And i prefer below one too cuz it's better as a Haskell's do-notation.

then you'd like to... reimplement 1+1 parser with State monad?
or extend parser to n+m?

**Comment by Iruyan-Zak** [comment]
I'll do in order...
- [x] reimplement 1+1 parser with State monad.
- [x] parse numbers(negatives, decimals)
- [x] extend parser to n+m

We should also consider integer-operation.
e.g.) On integer-integer-division, do we use float-point-number or fractional-number, or integer?

**Comment by Roadagain** [comment]
thx for ur answer.

i think about when each of them is needed:
- floating point numbers: use as a scientific calculator (if we do this, i wish repl)
- fractions: calculate exact answers
- integers: calculate Intuitive for computers or hold type info.

i feel integers the best and easiest for implement.
i need fractions as a library, not as a norm.

**Comment by Iruyan-Zak** [comment]
I started with parsing natural number denoted by REGEX /0|[1-9][0-9]*/.
now I have `digit` function that parsing a char matches REGEX /[0-9]/,  and this function implemented with [`Prelude.isDigit`](http://hackage.haskell.org/package/base-4.9.1.0/docs/src/GHC.Unicode.html#isDigit) function.

How do I implement parsing one matches REGEX /[1-9]/?
(Use regex, make alteration of `Prelude.isDigit`, or other way.)

**Comment by Iruyan-Zak** [comment]
does this enchantment look good?

**Comment by Roadagain** [comment]
i guessed what you did.

but i think `isNonZeroDigit` shorter than yours as `isDigit c && c /= '0'`.
which is better?

**Comment by Iruyan-Zak** [comment]
It's true.  Fixing now.

**Comment by Iruyan-Zak** [comment]
How do I treat negative numbers?
Concretely, do we allow this expression? : "1+-2"

**Comment by Roadagain** [comment]
it is allowed in python, ruby, and js so we can allow it like them.
haskell doesnt allow it, but prefers to be mathematical.

tiny prefers to write easily, so i hope the expression will be allowed.

**Comment by Iruyan-Zak** [comment]
OK.  I feel that some troubles will occur around `-` operator later, but it is nothing to be good that fears it now.

**Comment by Iruyan-Zak** [comment]
I will implement parsers following in regex.
So I makeing
1. $a \cdot b$
2. $a | b$
3. $a*$
4. $a?$
where a, b are regex.

How naming 1-4 operation?  I am satisfied only that I named (3) "closure."
(In (1) and (2), I defined `<.>`, `<|>` as binary operators.  But I wanna make function applying all of parsers in it's `[]`.
In (3) and (4), Haskell disallow defining unary operators in normal way, so I'd like to define as normal function.)

**Comment by Roadagain** [comment]
i propose the names of (1) and (2).
1. "composition" / "composite"
1. "switch"

but (4) has no proposal... sry

**Comment by Iruyan-Zak** [comment]
I thank you for your response.

In result of my research, 
- (1) is called "concatenate" in formal language theory.
- (2) is named "choice" in Parsec library.
- (4) is named "optional" in Parsec library.

So I use the name mentioned above.

**Comment by Iruyan-Zak** [comment]
My code remains unnecessary `do` notations rather than `(<.>)` operator.
The reason is just only the order of implementation.

I mention [`closure`](https://github.com/kosen13s/tiny/blob/5-four-arithmetical-operation/src/TinyParser.hs#L149) and [`naturalNumber`](https://github.com/kosen13s/tiny/blob/5-four-arithmetical-operation/src/TokenParser.hs#L17) now.

Should I rewrite these functions?

**Comment by Roadagain** [comment]
of course, but please log changes of the implementation courses here or commits.

**Comment by Iruyan-Zak** [comment]
@Roadagain Is it OK?

**Comment by Roadagain** [comment]
@Iruyan-Zak ok, great job.

btw, i can see closure as  `(p <.> closure p) <|> epsilon`.
i guess it should be `p <.> (closure p <|> epsilon)`, should not?

**Comment by Roadagain** [comment]
sry, i mistaked. `closure` is not wrong.

**Comment by Iruyan-Zak** [comment]
OK, I cannot find to do in this issue.
So I'm going to create PR.

**Comment by Iruyan-Zak** [comment]
I'm aware that I parse four-arithmetical-operation but not calculate it.
In my opinion, calculate is related in execution or code generating.
So I want to focus on parsing in this issue.

**Comment by Roadagain** [comment]
ok, so i wish to rename this issue "Parsing four-arithmetical-operations" for looking back.

**Comment by Iruyan-Zak** [comment]
Done it.
And I create PR #8.

**Comment by Roadagain** [comment]
thx and i will merge it after ci checks.

**Comment by Roadagain** [comment]
close via 8404e98
