### ISSUE TITLE
Rethink about tokens' data types

### ISSUE THREAD

**Issue by Roadagain** [kosen13s/tiny#9]
@Iruyan-Zak has implemented parsers but token data is returned as string now.
i and he talk on slack we should return in another way.

so rethink about tokens' data types.

**Comment by Iruyan-Zak** [comment]
OK.  Then I change the definition of `Parser` to polymorphic.
And then I define a type named `Token`, which will be the part of the return type of `naturalNumber` and more.

**Comment by Iruyan-Zak** [comment]
Probably you think that, some parsers should return a expression.
So I'm planning some data types.

- [`Expression`] a `Term` or a binary tree of ones whose node is a binary operator which includes multiply operator `*`.
- [`Term`] a `XXX` and a list of unary operators optionally.
- [`XXX`] an identifier, a literal, or a parenthesized `Expression`.  This means "can become `Expression` without other tokens."

So, my questions are
1. Does my plan look cool?
2. If so, how should I name `XXX`?

**Comment by Roadagain** [comment]
it looks cool and great.

In "Progamming in Haskell", `XXX` is called as `factor`.

if it is needed, i will show you published sources in "Programming in Haskell".

**Comment by Roadagain** [comment]
i've thought `'+'` should be in `prefixOperator` cuz tiny should operate `"+2"` as `2`.

i need your opinion.

**Comment by Iruyan-Zak** [comment]
Mathematically, it is better to add `+`,  but I think 
it is unnecessary.
Have you ever used unary `+` operator in any programming languages?

**Comment by Roadagain** [comment]
never... it is really unnecessary lol

**Comment by Iruyan-Zak** [comment]
In JavaScript, `+true` has a meaning to cast boolean to int as a kind of hack.
But it is better than being ready for hacking to support such needs with honesty way.

**Comment by Iruyan-Zak** [comment]
Can I create PR?

**Comment by Roadagain** [comment]
yes, i will merge it.

**Comment by Roadagain** [comment]
close via dfc3313
